project:
  type: website

website:
  title: "apache-sedona-r-tutorial.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: preprocessing_one.qmd
        text: Chapter One
      - href: preprocessing_two.qmd
        text: Chapter Two
      - href: preprocessing_three.qmd
        text: Chapter Three

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

