project:
  type: book
  output-dir: docs

book:
  title: "Processing Big Data with Delta Lake, Sparklyr, and Apache Sedona in R"
  author: "Rodgers Iradukunda"
  search: true
  site-url: https://rog33zy.github.io/apache-sedona-r-tutorial.github.io/
  repo-url: https://github.com/rog33zy/apache-sedona-r-tutorial.github.io
  repo-actions: [edit, issue]
  sidebar:
    style: docked
    background: light
  date: today
  chapters:
    - index.qmd
    - preprocessing_one.qmd
    - preprocessing_two.qmd
    - preprocessing_three.qmd
    - preprocessing_four.qmd
    - preprocessing_five.qmd

format:
  html:
    theme: cosmo  # or replace with [default, style/custom.scss] if you want custom styling
    fontsize: "20px"
    linestretch: 1.6
    smooth-scroll: true
    toc-depth: 3
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
    code-link: true
    code-tools:
      toggle: true
    highlight-style: printing
    code-block-bg: true
    code-overflow: wrap
    reference-location: margin
    mermaid:
      theme: neutral

editor: visual
