name: Quarto Publish

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      # Install system libraries needed for units, sf, etc.
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.4.0"  # Make sure to set this high enough for MASS and others

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.4.550"

      - name: Restore R packages
        run: Rscript -e 'renv::restore()'

      - name: Render Quarto Project
        run: quarto render --log-level=debug

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
